name: Build

on:
   push:
    branches: [ master ]
   pull_request:
    branches: [ master ]

jobs:
  BuildLinux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Make executable
      run: |
        chmod +x ./libogg/configure
        chmod +x ./libvorbis/configure

    - name: Configure Ogg
      run: ./configure
      working-directory: ./libogg/
    - name: Build Ogg
      run: make
      working-directory: ./libogg/

    - name: List files1
      run: ls -R
      shell: bash

    - name: Autogen
      run: ./autogen.sh
      working-directory: ./libvorbis/
    - name: Configure Vorbis
      run: ./configure
      working-directory: ./libvorbis/
    - name: Build Vorbis
      run: make
      working-directory: ./libvorbis/

    - name: List files 2
      run: ls -R
      shell: bash
