name: Build

on:
   push:
    branches: [ master ]
   pull_request:
    branches: [ master ]

jobs:
  BuildLinux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Make executable
      run: |
        chmod +x ./libogg/configure
        chmod +x ./libogg/install-sh
        chmod +x ./libvorbis/autogen.sh
        chmod +x ./libvorbis/configure

    - name: Configure Ogg
      run: ./configure
      working-directory: ./libogg/
    - name: Build Ogg
      run: sudo make
      working-directory: ./libogg/
    - name: make check
      run: sudo make check
      working-directory: ./libogg/
    - name: make distcheck
      run: sudo make distcheck
      working-directory: ./libogg/

    - name: List files1
      run: ls -R
      shell: bash

    - name: Upload Ogg
      uses: actions/upload-artifact@v2
      with:
        name: LibOgg
        path: /home/runner/work/OggVorbisBuilds/OggVorbisBuilds/libogg/libogg-1.3.5.zip
        if-no-files-found: error

#    - name: Install
#      run: ./install-sh
#      working-directory: ./libogg/

#    - name: Autogen
#      run: ./autogen.sh
#      working-directory: ./libvorbis/
#    - name: Configure Vorbis
#      run: ./configure
#      working-directory: ./libvorbis/
#    - name: Build Vorbis
#      run: make
#      working-directory: ./libvorbis/

#    - name: List files 2
#      run: ls -R
#      shell: bash
