name: Build

on:
   push:
    branches: [ master ]
   pull_request:
    branches: [ master ]

jobs:
  BuildLinux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure Ogg
      run: sudo /home/runner/OggVorbisBuilds/OggVorbisBuilds/libogg/configure
    - name: Build Ogg
      run: make
      working-directory: ./libogg/

    - name: Configure Vorbis
      run: sudo ./configure
      working-directory: ./libvorbis/
    - name: Build Vorbis
      run: make
      working-directory: ./libvorbis/
