name: Build

on:
   push:
    branches: [ master ]
   pull_request:
    branches: [ master ]

jobs:
  BuildLinux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Make executable
      run: |
        chmod +x ./libogg/configure
        chmod +x ./libogg/install-sh
        chmod +x ./libvorbis/autogen.sh
        chmod +x ./libvorbis/configure

    - name: Configure Ogg
      run: cmake -B ./build/
      working-directory: ./libogg/
    - name: Build Ogg
      run: cmake --build .
      working-directory: ./libogg/build/

    - name: List files1
      run: ls -R
      shell: bash

#    - name: Install
#      run: ./install-sh
#      working-directory: ./libogg/

#    - name: Autogen
#      run: ./autogen.sh
#      working-directory: ./libvorbis/
#    - name: Configure Vorbis
#      run: ./configure
#      working-directory: ./libvorbis/
#    - name: Build Vorbis
#      run: make
#      working-directory: ./libvorbis/

#    - name: List files 2
#      run: ls -R
#      shell: bash
